#!/bin/csh
#SBATCH --job-name=tRAMD_equil_GA4
#SBATCH --ntasks=55
#SBATCH --cpus-per-task=2
#SBATCH --time=1-00:00:00
#SBATCH --mem-per-cpu=100  # memory/cpu (in MB)
#SBATCH --error=error_equilNAMD.err 
#SBATCH --output=equilNAMD.log
##SBATCH --partition=long 
cd $SLURM_SUBMIT_DIR

module load NAMD

#srun namd2 amber2namd_heating.in  > amber2namd_heating.out
srun namd2 amber2namd_equilibr.in > amber2namd_equilibr.out
